source 'http://rubygems.org'

gem 'rails', '3.0.9'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'devise'

gem 'netzke-core',     :path => File.expand_path('../vendor/gems/netzke-core', __FILE__)
gem 'netzke-basepack', :path => File.expand_path('../vendor/gems/netzke-basepack', __FILE__)

group :development, :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'rspec-rails', "~> 2.0.0"
  gem 'spork'
  gem 'launchy'    # So you can do Then show me the page
  gem 'factory_girl'
end

group :development do
  gem 'mysql2', '~> 0.2.0'
end

group :test do
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'pickle'
  gem 'database_cleaner'
end
